version: 0.1

default:
  global:
    parameters:
      stack_name: sam-feedbackform
      # tags:
      #   - feebackform
      timeout: 300

      region: us-east-1
  build:
    parameters:
      cached: false
      parallel: true

  validate:
    parameters:
      lint: true

  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      confirm_changeset: true
      resolve_s3: true
      timeout: 300

      s3_prefix: sam-feedbackform
      region: us-east-1
      image_repositories: []
  package:
    parameters:
      resolve_s3: false

  sync:
    parameters:
      watch: true

  local_start_api:
    parameters:
      warm_containers: EAGER

  local_start_lambda:
    parameters:
      warm_containers: EAGER

dev:
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      stack_name: sam-feedbackform-dev
      s3_bucket: sam-feedbackform-bucket-dev
      timeout: 300
      parameter_overrides:
      - DeploymentBucket=sam-feedbackform-artifacts-dev
      - Region=us-east-1
      - Stage=dev
      - LogLevel=debug

prod:
  deploy:
    parameters:
      capabilities: CAPABILITY_IAM
      stack_name: sam-feedbackform-prod
      s3_bucket: sam-feedbackform-bucket-prod
      timeout: 300
      parameter_overrides:
      - DeploymentBucket=sam-feedbackform-artifacts-prod
      - Region=us-east-1
      - Stage=prod
      - LogLevel=fatal
